name: homenet2mqtt
version: 0.0.1
slug: h2m
description: Bridge between RS485 HomeNet devices and MQTT.
url: https://github.com/woooook/RS485-HomeNet-to-MQTT-bridge
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
image: "woooook/homenet2mqtt"
options:
  log_level: info
  mqtt_url: mqtt://core-mosquitto:1883
  mqtt_topic_prefix: homenet
  serial_port: /dev/ttyUSB0
  config_file: samsung_sds.homenet_bridge.yaml
schema:
  log_level: list(debug, info, warn, error)
  mqtt_url: str
  mqtt_topic_prefix: str
  serial_port: device
  config_file: str
ports:
  3000/tcp: 3000
