name: Homenet2MQTT
version: 0.0.13
slug: h2m
description: Bridge between RS485 HomeNet devices and MQTT.
url: https://github.com/woooook/RS485-HomeNet-to-MQTT-bridge
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
image: "nubiz/homenet2mqtt"
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
options:
  log_level: info
  mqtt_url: mqtt://core-mosquitto:1883
  mqtt_need_login: true
  mqtt_user: "addons"
  mqtt_passwd: ""
  mqtt_topic_prefix: homenet
  serial_port: 
  config_file: samsung_sds.homenet_bridge.yaml
hassio_role: default
hassio_api: true
services:
  - mqtt:need
schema:
  log_level: list(trace|debug|info|warning|error|fatal)
  mqtt_url: str
  mqtt_need_login: bool
  mqtt_user: str?
  mqtt_passwd: str?
  mqtt_topic_prefix: str
  serial_port: str
  config_file: str
ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: mdi:crop-landscape
