homenet_bridge:
  serial:
    portId: cvnet_main
    path: 192.168.0.83:8888
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

  packet_defaults: # New section for global packet defaults
    rx_timeout: 10ms
    tx_delay: 10ms
    tx_timeout: 200ms
    tx_retry_cnt: 5

    rx_header: [0xF7]
    tx_header: [0xF7]
    rx_footer: [0xAA]
    tx_footer: [0xAA]
    rx_checksum: add_no_header
    tx_checksum: add_no_header

  light:
    - id: 'room_0_light_1'
      name: 'Room 0 Light 1'
      state:
        data: [0x20, 0x01, 0x21]
      state_on:
        offset: 5
        data: [0x01]
      state_off:
        offset: 5
        data: [0x00]
      command_on:
        data: [0x20, 0x21, 0x01, 0x11, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]
      command_off:
        data: [0x20, 0x21, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]

    - id: 'room_0_light_2'
      name: 'Room 0 Light 2'
      state:
        data: [0x20, 0x01, 0x21]
      state_on:
        offset: 6
        data: [0x01]
      state_off:
        offset: 6
        data: [0x00]
      command_on:
        data: [0x20, 0x21, 0x01, 0x12, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]
      command_off:
        data: [0x20, 0x21, 0x01, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]

    - id: 'room_0_light_3'
      name: 'Room 0 Light 3'
      state:
        data: [0x20, 0x01, 0x21]
      state_on:
        offset: 7
        data: [0x01]
      state_off:
        offset: 7
        data: [0x00]
      command_on:
        data: [0x20, 0x21, 0x01, 0x13, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]
      command_off:
        data: [0x20, 0x21, 0x01, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x21, 0x9F]

    - id: 'room_1_light_1'
      name: 'Room 1 Light 1'
      state:
        data: [0x20, 0x01, 0x22]
      state_on:
        offset: 5
        data: [0x01]
      state_off:
        offset: 5
        data: [0x00]
      command_on:
        data: [0x20, 0x22, 0x01, 0x11, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x22, 0x9F]
      command_off:
        data: [0x20, 0x22, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x22, 0x9F]

  fan:
    - id: 'fan_1'
      name: 'Fan 1'
      state:
        data: [0x20, 0x01, 0x71]
      state_on:
        offset: 5
        data: [0x01]
      state_off:
        offset: 5
        data: [0x00]
      command_on:
        data: [0x20, 0x71, 0x01, 0x11, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x71, 0x91]
      command_off:
        data: [0x20, 0x71, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x71, 0x91]
      command_speed: >-
        [[0x20, 0x71, 0x01, 0x02, x, 0x00, 0x00], [0x60, 0x71, 0x01, 0x02, x]]
      state_speed:
        offset: 7
        signed: False

  valve:
    - id: 'gas_valve'
      name: 'Gas Valve'
      device_class: gas
      state:
        data: [0x20, 0x01, 0x11]
      state_closed:
        offset: 5
        data: [0x00]
      state_open:
        offset: 5
        data: [0x01]
      command_close:
        data: [0x20, 0x11, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x20, 0x01, 0x11, 0x91]

  climate:
    - id: 'heater_1'
      name: 'Heater 1'
      visual:
        min_temperature: 6 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x20, 0x01, 0x4A]
      state_temperature_current:
        offset: 6
      state_temperature_target: >-
        bitAnd(data[4], 0x7F)
      state_off:
        offset: 5
        data: [0x00]
        mask: [0x80]
      state_heat:
        offset: 5
        data: [0x80]
        mask: [0x80]
      command_off: >-
        [[0x20, 0x41, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x41, 0x91]]
      command_heat: >-
        [[0x20, 0x41, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x41, 0x91]]
      command_temperature: >-
        [[0x20, 0x41, 0x01, 0x11, int(x) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x41, 0x91]]

    - id: 'heater_2'
      name: 'Heater 2'
      visual:
        min_temperature: 6 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x20, 0x01, 0x4A]
      state_temperature_current:
        offset: 8
      state_temperature_target: >-
        bitAnd(data[6], 0x7F)
      state_off:
        offset: 7
        data: [0x00]
        mask: [0x80]
      state_heat:
        offset: 7
        data: [0x80]
        mask: [0x80]
      command_off: >-
        [[0x20, 0x42, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x42, 0x91]]
      command_heat: >-
        [[0x20, 0x42, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x42, 0x91]]
      command_temperature: >-
        [[0x20, 0x42, 0x01, 0x11, int(x) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x42, 0x91]]

    - id: 'heater_3'
      name: 'Heater 3'
      visual:
        min_temperature: 6 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x20, 0x01, 0x4A]
      state_temperature_current:
        offset: 10
      state_temperature_target: >-
        bitAnd(data[8], 0x7F)
      state_off:
        offset: 9
        data: [0x00]
        mask: [0x80]
      state_heat:
        offset: 9
        data: [0x80]
        mask: [0x80]
      command_off: >-
        [[0x20, 0x43, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x43, 0x91]]
      command_heat: >-
        [[0x20, 0x43, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x43, 0x91]]
      command_temperature: >-
        [[0x20, 0x43, 0x01, 0x11, int(x) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x43, 0x91]]

    - id: 'heater_4'
      name: 'Heater 4'
      visual:
        min_temperature: 6 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x20, 0x01, 0x4A]
      state_temperature_current:
        offset: 12
      state_temperature_target: >-
        bitAnd(data[10], 0x7F)
      state_off:
        offset: 11
        data: [0x00]
        mask: [0x80]
      state_heat:
        offset: 11
        data: [0x80]
        mask: [0x80]
      command_off: >-
        [[0x20, 0x44, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x44, 0x91]]
      command_heat: >-
        [[0x20, 0x44, 0x01, 0x11, int(has(state.target_temperature) ? state.target_temperature : 0) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x44, 0x91]]
      command_temperature: >-
        [[0x20, 0x44, 0x01, 0x11, int(x) + 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x20, 0x01, 0x44, 0x91]]

  sensor:
    - id: 'elevator_floors'
      name: 'Elevator Floors'
      icon: 'mdi:elevator'
      state:
        data: [0x20, 0x01, 0x22, 0x81]
      state_number:
        offset: 5

  button:
    - id: 'elevator_call'
      name: 'Elevator Call'
      icon: 'mdi:elevator'
      command_press:
        data: [0x20, 0x01, 0x81, 0x81, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      discovery_linked_id: 'elevator_floors'
