homenet_bridge:
  serial:
    portId: kocom_thinks
    path: 192.168.0.83:8888
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

  packet_defaults: # New section for global packet defaults
    rx_timeout: 10ms
    rx_length: 21
    tx_delay: 100ms
    tx_timeout: 500ms
    tx_retry_cnt: 3

    rx_header: [0xAA, 0x55]
    rx_footer: [0x0D, 0x0D]
    tx_header: [0xAA, 0x55]
    tx_footer: [0x0D, 0x0D]

    rx_checksum: add_no_header
    tx_checksum: add_no_header

  light:
    - id: 'livingroom_light_1'
      name: 'Living Room Light 1'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 8
        data: [0xff]
      state_off:
        offset: 8
        data: [0x00]
      command_on: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0xff, light2_on, light3_on, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_off: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0x00, light2_on, light3_on, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x0e,
            0x00,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'livingroom_light_2'
      name: 'Living Room Light 2'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 9
        data: [0xff]
      state_off:
        offset: 9
        data: [0x00]
      command_on: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1_on, 0xff, light3_on, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_off: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1_on, 0x00, light3_on, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]

    - id: 'livingroom_light_3'
      name: 'Living Room Light 3'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 10
        data: [0xff]
      state_off:
        offset: 10
        data: [0x00]
      command_on: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1_on, light2_on, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_off: >-




        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1_on, light2_on, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]

  climate:
    - id: 'livingroom_heater'
      name: 'Living Room Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x00]
        mask: [0xF0]
      state_heat:
        offset: 8
        data: [0x10]
        mask: [0xF0]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x00,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'room_1_heater'
      name: 'Room 1 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x01]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
        length: 1
        precision: 0
      state_temperature_target:
        offset: 10
        length: 1
        precision: 0
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x01,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'room_2_heater'
      name: 'Room 2 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x02]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x02,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'room_3_heater'
      name: 'Room 3 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x03]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x03,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'room_4_heater'
      name: 'Room 4 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x04]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x04,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

    - id: 'room_5_heater'
      name: 'Room 5 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x05]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
        length: 1
        precision: 0
      state_temperature_target:
        offset: 10
        length: 1
        precision: 0
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-

        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x36,
            0x05,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

  valve:
    - name: 'Gas Valve'
      state:
        data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_open:
        offset: 7
        data: [0x01]
      state_closed:
        offset: 7
        data: [0x01]
        inverted: true
      command_close:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x2c,
            0x00,
            0x01,
            0x00,
            0x02,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x2c,
            0x00,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

  fan:
    - name: 'Navien Ventilator'
      state:
        data: [0x30, 0xd0, 0x00, 0x48, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 8
        data: [0x11]
      state_off:
        offset: 8
        data: [0x00]
      state_speed: >-
        data[10] == 0x40 ? 1 :
        data[10] == 0x80 ? 2 :
        data[10] == 0xc0 ? 3 : 0
      command_on:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x01,
            0x00,
            0x48,
            0x00,
            0x00,
            0x11,
            0x01,
            0x40,
            0x17,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]
      command_off:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x01,
            0x00,
            0x48,
            0x00,
            0x00,
            0x00,
            0x01,
            0x00,
            0x17,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]
      command_speed: >-

        [[0x30, 0xbc, 0x00, 0x01, 0x00, 0x48, 0x00, 0x00, 0x11, 0x01, speed, 0x17, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x48,
            0x00,
            0x01,
            0x00,
            0x3a,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]

  sensor:
    - name: 'Elevator Floors'
      icon: 'mdi:elevator'
      unit_of_measurement: '층'
      state:
        data: [0x30, 0xd0, 0x00, 0x01, 0x00, 0x44, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff, 0xff, 0xff]
      state_number:
        offset: 9
    - name: 'Livingroom Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12
    - name: 'Room 1 Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x01]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12
    - name: 'Room 2 Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x02]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12
    - name: 'Room 3 Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x03]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12
    - name: 'Room 4 Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x04]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12
    - name: 'Room 5 Temperature'
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x05]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      unit_of_measurement: '°C'
      icon: 'mdi:thermometer'
      device_class: 'temperature'
      state_class: 'measurement'
      state_number:
        offset: 12

  text_sensor:
    - name: 'Elevator Direction'
      icon: 'mdi:elevator'
      state:
        data: [0x30, 0xd0, 0x00, 0x01, 0x00, 0x44, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff, 0xff, 0xff]
      state_text: >-
        data[8] == 0x00 ? "정지" :
        data[8] == 0x01 ? "하강" :
        data[8] == 0x02 ? "상승" :
        data[8] == 0x03 ? "도착" : "Unknown"

  switch:
    - name: 'Elevator Call'
      icon: 'mdi:elevator'
      optimistic: true
      state_off:
        data: [0x30, 0x00, 0x00, 0x44]
        mask: [0xff, 0x00, 0xff, 0xff]
      command_on:
        data:
          [
            0x30,
            0xbc,
            0x00,
            0x01,
            0x00,
            0x44,
            0x00,
            0x01,
            0x03,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
          ]
        ack: [0x30, 0xdc]
  button:
    - name: 'Refresh'
      icon: 'mdi:refresh-circle'

automation:
  - id: 'lights_refresh'
    trigger:
      - type: schedule
        every: 2h
    action:
      - type: command
        id: livingroom_light_1
        command: command_update

  - id: 'heaters_refresh'
    trigger:
      - type: schedule
        every: 2h
    action:
      - type: command
        id: livingroom_heater
        command: command_update
      - type: command
        id: room_1_heater
        command: command_update
      - type: command
        id: room_2_heater
        command: command_update
      - type: command
        id: room_3_heater
        command: command_update
      - type: command
        id: room_4_heater
        command: command_update
      - type: command
        id: room_5_heater
        command: command_update

  - id: 'gas_valve_refresh'
    trigger:
      - type: schedule
        every: 2h
    action:
      - type: command
        id: gas_valve
        command: command_update

  - id: 'ventilator_refresh'
    trigger:
      - type: schedule
        every: 2h
    action:
      - type: command
        id: navien_ventilator
        command: command_update
