homenet_bridge:
  serial:
    portId: kocom_door
    path: 192.168.0.83:8888
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

  packet_defaults: # New section for global packet defaults
    rx_timeout: 10ms
    tx_delay: 50ms
    tx_timeout: 500ms
    tx_retry_cnt: 3

    rx_footer: [0x0D, 0x0D]
    tx_footer: [0x0D, 0x0D]

  binary_sensor:
    - name: 'Bell'
      icon: 'mdi:bell-ring'
      state:
        data: [0xAA, 0x55, 0x70, 0x90, 0x02, 0x02]
        mask: [0xFF, 0xFF, 0xF0, 0xF0, 0xFF, 0xFF]
      state_on:
        offset: 15
        data: [0x01]
      state_off:
        offset: 15
        data: [0x02]

    - name: 'Bell Common'
      icon: 'mdi:bell-ring'
      state:
        data: [0xAA, 0x55, 0x70, 0x90, 0x02, 0x08]
        mask: [0xFF, 0xFF, 0xF0, 0xF0, 0xFF, 0xFF]
      state_on:
        offset: 15
        data: [0x01]
      state_off:
        offset: 15
        data: [0x02]

  button:
    - name: 'Call Common'
      icon: 'mdi:phone'
      command_press:
        data:
          [
            0xAA,
            0x55,
            0x79,
            0xBC,
            0x08,
            0x02,
            0x00,
            0xFF,
            0xFF,
            0xFF,
            0xFF,
            0x61,
            0xFF,
            0xFF,
            0xFF,
            0x03,
            0x00,
            0x26,
            0x95,
          ]
        ack: [0x0F, 0x03]

    - name: 'Open Common'
      icon: 'mdi:door-sliding-open'
      command_press:
        data:
          [
            0xAA,
            0x55,
            0x79,
            0xBC,
            0x08,
            0x02,
            0x00,
            0xFF,
            0xFF,
            0xFF,
            0xFF,
            0x61,
            0xFF,
            0xFF,
            0xFF,
            0x24,
            0x00,
            0xB9,
            0xE4,
          ]
        ack: [0x0F, 0x24]

    - name: 'Call'
      icon: 'mdi:phone'
      command_press:
        data:
          [
            0xAA,
            0x55,
            0x79,
            0xBC,
            0x02,
            0x02,
            0x00,
            0x31,
            0xFF,
            0xFF,
            0xFF,
            0x61,
            0xFF,
            0xFF,
            0xFF,
            0x03,
            0x00,
            0x08,
            0xD3,
          ]
        ack: [0x0F, 0x03]

    - name: 'Open'
      icon: 'mdi:door-sliding-open'
      command_press:
        data:
          [
            0xAA,
            0x55,
            0x79,
            0xBC,
            0x02,
            0x02,
            0x00,
            0x31,
            0xFF,
            0xFF,
            0xFF,
            0x61,
            0xFF,
            0xFF,
            0xFF,
            0x24,
            0x00,
            0x97,
            0xA2,
          ]
        ack: [0x0F, 0x24]

  switch:
    - name: 'Auto Open Common'
      icon: 'mdi:door-open'

    - name: 'Auto Open'
      icon: 'mdi:door-open'
