homenet_bridge:
  serial:
    baud_rate: 9600
    data_bits: 8
    parity: none
    stop_bits: 1
  
  packet_defaults:
    rx_header: []
    tx_header: []
    rx_footer: []
    tx_footer: []
    rx_checksum: none
    tx_checksum: none

  devices:
    - name: "Commax Wallpad"
      entities:
        - type: light
          id: "light_1"
          name: "조명 1"
          state:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_on:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_off:
            data: [0x00]
            offset: 1
            mask: 0x01
          command_on:
            cmd: [0x31, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x01, 0x01]
          command_off:
            cmd: [0x31, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x00, 0x01]
          packet_parameters:
            rx_header: [0xB0]
            tx_header: []
        - type: light
          id: "light_2"
          name: "조명 2"
          state:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_on:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_off:
            data: [0x00]
            offset: 1
            mask: 0x01
          command_on:
            cmd: [0x31, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x01, 0x02]
          command_off:
            cmd: [0x31, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x00, 0x02]
          packet_parameters:
            rx_header: [0xB0]
            tx_header: []
        - type: light
          id: "light_3"
          name: "조명 3"
          state:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_on:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_off:
            data: [0x00]
            offset: 1
            mask: 0x01
          command_on:
            cmd: [0x31, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x01, 0x03]
          command_off:
            cmd: [0x31, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x00, 0x03]
          packet_parameters:
            rx_header: [0xB0]
            tx_header: []
        - type: light
          id: "light_4"
          name: "조명 4"
          state:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_on:
            data: [0x01]
            offset: 1
            mask: 0x01
          state_off:
            data: [0x00]
            offset: 1
            mask: 0x01
          command_on:
            cmd: [0x31, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x01, 0x04]
          command_off:
            cmd: [0x31, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0xB1, 0x00, 0x04]
          packet_parameters:
            rx_header: [0xB0]
            tx_header: []

        - type: climate
          id: "heater_1"
          name: "난방 1"
          state:
            data: []
            offset: 1
            mask: 0x81
          state_temperature_current:
            offset: 3
            length: 1
            decode: bcd
          state_temperature_target:
            offset: 4
            length: 1
            decode: bcd
          state_off:
            data: [0x00]
            offset: 1
            mask: 0x81
          state_heat:
            data: [0x01]
            offset: 1
            mask: 0x81
          command_off:
            cmd: [0x04, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0x84, 0x80, 0x01]
          command_heat:
            cmd: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00, 0x00]
            ack: [0x84, 0x81, 0x01]
          command_temperature:
            cmd: [0x04, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00]
            value_offset: 3
            value_encode: bcd
          packet_parameters:
            rx_header: [0x82]
            tx_header: []

        - type: valve
          id: "gas_valve"
          name: "가스 밸브"
          state:
            data: []
            offset: 1
            mask: 0x80
          state_open:
            data: [0x80]
            offset: 1
            mask: 0x80
          state_closed:
            data: [0x40]
            offset: 1
            mask: 0x40
          command_close:
            cmd: [0x11, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack: [0x91, 0x88, 0x88]
          packet_parameters:
            rx_header: [0x90]
            tx_header: []

        - type: sensor
          id: "elevator_floor"
          name: "엘리베이터 층수"
          state_number:
            offset: 2
            length: 1
            precision: 0
          packet_parameters:
            rx_header: [0x23]
            tx_header: []
        - type: button
          id: "elevator_call"
          name: "엘리베이터 호출"
          command_press:
            cmd: [0xA0, 0x01, 0x01, 0x00, 0x08, 0x15, 0x00, 0x00]
            ack: [0x23]
          packet_parameters:
            rx_header: []
            tx_header: []
