homenet_bridge:
  serial:
    baud_rate: 3880
    data_bits: 8
    parity: none
    stop_bits: 1
  
  packet_defaults:
    rx_timeout: 10ms
    tx_delay: 50ms
    tx_timeout: 500ms
    tx_retry_cnt: 3
    rx_header: [0x7F]
    tx_header: [0x7F]
    rx_footer: [0xEE]
    tx_footer: [0xEE]
    rx_checksum: none # Not explicitly defined
    tx_checksum: none # Not explicitly defined

  devices:
    - name: "Hyundai Door"
      entities:
        - type: binary_sensor
          id: "door_bell"
          name: "Door Bell"
          state:
            data: [0xB4, 0x00, 0x00]
            mask: [0xB4, 0xFF, 0xFF]
          state_on:
            offset: 0
            data: [0xB5]
          state_off:
            offset: 0
            data: [0xB6]
        - type: binary_sensor
          id: "door_bell_common"
          name: "Door Bell Common"
          state:
            data: [0x58, 0x00, 0x00]
            mask: [0x58, 0xFF, 0xFF]
          state_on:
            offset: 0
            data: [0x5A]
          state_off:
            offset: 0
            data: [0x5C]

        - type: button
          id: "door_open_common"
          name: "Door Open Common"
          command_press:
            cmd: [0x61, 0x00, 0x00]
        - type: button
          id: "door_open"
          name: "Door Open"
          command_press:
            cmd: [0xB4, 0x00, 0x00]

        - type: switch
          id: "door_call_common"
          name: "Door Call Common"
          command_on:
            cmd: [0x5F, 0x00, 0x00]
          command_off:
            cmd: [0x60, 0x00, 0x00]
        - type: switch
          id: "door_call"
          name: "Door Call"
          command_on:
            cmd: [0xB7, 0x00, 0x00]
          command_off:
            cmd: [0xBB, 0x00, 0x00]
