homenet_bridge:
  serial:
    baud_rate: 9600
    data_bits: 8
    parity: none
    stop_bits: 1
  
  packet_defaults:
    rx_header: []
    tx_header: []
    rx_footer: []
    tx_footer: []
    rx_checksum: none
    tx_checksum: none

  devices:
    - name: "Kocom Wallpad"
      entities:
        - type: light
          id: "light_1"
          name: "조명 1"
          state:
            data: []
            offset: 4
            mask: 0x01
          state_on:
            data: [0x01]
            offset: 4
            mask: 0x01
          state_off:
            data: [0x00]
            offset: 4
            mask: 0x01
          command_on:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x01, 0x00, 0xBC]
            ack: []
          command_off:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x01, 0x01, 0xBD]
            ack: []
          packet_parameters:
            rx_header: [0xAA, 0x55, 0x0B, 0x01]
            tx_header: []
        - type: light
          id: "light_2"
          name: "조명 2"
          state:
            data: []
            offset: 4
            mask: 0x02
          state_on:
            data: [0x02]
            offset: 4
            mask: 0x02
          state_off:
            data: [0x00]
            offset: 4
            mask: 0x02
          command_on:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x02, 0x00, 0xBD]
            ack: []
          command_off:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x02, 0x01, 0xBE]
            ack: []
          packet_parameters:
            rx_header: [0xAA, 0x55, 0x0B, 0x01]
            tx_header: []
        - type: light
          id: "light_all"
          name: "모든 조명"
          command_on:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x0F, 0x00, 0xCC]
            ack: []
          command_off:
            cmd: [0xAA, 0x55, 0x08, 0x02, 0x01, 0x0F, 0x01, 0xCD]
            ack: []
          packet_parameters:
            rx_header: []
            tx_header: []

        - type: climate
          id: "heater_1"
          name: "난방 1"
          state:
            data: []
            offset: 4
            mask: 0x01
          state_temperature_current:
            offset: 5
            length: 1
            precision: 0
          state_temperature_target:
            offset: 6
            length: 1
            precision: 0
          state_off:
            data: [0x00]
            offset: 4
            mask: 0x01
          state_heat:
            data: [0x01]
            offset: 4
            mask: 0x01
          command_off:
            cmd: [0xAA, 0x55, 0x0A, 0x02, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00]
            ack: []
          command_heat:
            cmd: [0xAA, 0x55, 0x0A, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00]
            ack: []
          command_temperature:
            cmd: [0xAA, 0x55, 0x0A, 0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00]
            value_offset: 6
            value_encode: none
          packet_parameters:
            rx_header: [0xAA, 0x55, 0x1D, 0x01]
            tx_header: []

        - type: button
          id: "elevator_call"
          name: "엘리베이터 호출"
          command_press:
            cmd: [0xAA, 0x55, 0x06, 0x41, 0x01, 0x0C]
            ack: []
          packet_parameters:
            rx_header: []
            tx_header: []
