homenet_bridge:
  serial:
    baud_rate: 9600
    data_bits: 8
    parity: even # Original was EVEN, mapping to even
    stop_bits: 1
  
  packet_defaults:
    rx_timeout: 10ms
    tx_delay: 50ms
    tx_timeout: 500ms
    tx_retry_cnt: 3
    rx_header: [0xB0]
    tx_header: [] # Not explicitly defined in original, assuming entity-specific
    rx_footer: [] # Not explicitly defined in original
    tx_footer: [] # Not explicitly defined in original
    rx_checksum: custom # Original was lambda
    tx_checksum: custom # Original was lambda
    # Original rx_checksum lambda:
    # uint8_t crc = 0xB0;
    # for (size_t i = 0; i < len; i++)
    #   crc ^= data[i];
    # if (data[0] < 0x7C) crc ^= 0x80;
    # return crc;
    # Original tx_checksum lambda:
    # uint8_t crc = 0x00;
    # for (size_t i = 0; i < len; i++)
    #   crc ^= data[i];
    # crc ^= 0x80;
    # return crc;

  devices:
    - name: "Samsung SDS Wallpad"
      entities:
        - type: button
          id: "gas_valve_close"
          name: "Gas Valve Close"
          command_press:
            cmd: [0xAB, 0x78, 0x00]
            ack: [0x78]

        - type: light
          id: "light_1"
          name: "Light 1"
          state:
            data: [0x79, 0x31]
          state_on:
            offset: 2
            data: [0x01]
            mask: 0x01
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x01
          command_on:
            cmd: [0xAC, 0x7A, 0x01, 0x01]
            ack: [0x7A, 0x01, 0x01]
          command_off:
            cmd: [0xAC, 0x7A, 0x01, 0x00]
            ack: [0x7A, 0x01, 0x00]
        - type: light
          id: "light_2"
          name: "Light 2"
          state:
            data: [0x79, 0x31]
          state_on:
            offset: 2
            data: [0x02]
            mask: 0x02
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x02
          command_on:
            cmd: [0xAC, 0x7A, 0x02, 0x01]
            ack: [0x7A, 0x02, 0x01]
          command_off:
            cmd: [0xAC, 0x7A, 0x02, 0x00]
            ack: [0x7A, 0x02, 0x00]
        - type: light
          id: "light_3"
          name: "Light 3"
          state:
            data: [0x79, 0x31]
          state_on:
            offset: 2
            data: [0x04]
            mask: 0x04
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x04
          command_on:
            cmd: [0xAC, 0x7A, 0x03, 0x01]
            ack: [0x7A, 0x03, 0x01]
          command_off:
            cmd: [0xAC, 0x7A, 0x03, 0x00]
            ack: [0x7A, 0x03, 0x00]
        - type: light
          id: "light_4"
          name: "Light 4"
          state:
            data: [0x79, 0x24]
          state_on:
            offset: 2
            data: [0x01]
            mask: 0x01
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x01
          command_on:
            cmd: [0xAC, 0x7A, 0x04, 0x01]
            ack: [0x7A, 0x04, 0x01]
          command_off:
            cmd: [0xAC, 0x7A, 0x04, 0x00]
            ack: [0x7A, 0x04, 0x00]
        - type: light
          id: "light_5"
          name: "Light 5"
          state:
            data: [0x79, 0x24]
          state_on:
            offset: 2
            data: [0x02]
            mask: 0x02
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x02
          command_on:
            cmd: [0xAC, 0x7A, 0x05, 0x01]
            ack: [0x7A, 0x05, 0x01]
          command_off:
            cmd: [0xAC, 0x7A, 0x05, 0x00]
            ack: [0x7A, 0x05, 0x00]

        - type: climate
          id: "room_0_heater"
          name: "Room 0 Heater"
          visual:
            min_temperature: 5
            max_temperature: 40
            temperature_step: 1
          state:
            data: [0x7C, 0x01]
          state_temperature_current:
            offset: 4
            length: 1
            precision: 0
          state_temperature_target:
            offset: 3
            length: 1
            precision: 0
          state_off:
            offset: 2
            data: [0x00]
            mask: 0x01
          state_heat:
            offset: 2
            data: [0x01]
            mask: 0x01
          command_off:
            cmd: [0xAE, 0x7D, 0x01, 0x00, 0x00, 0x00, 0x00]
            ack: [0x7D, 0x01, 0x00]
          command_heat:
            cmd: [0xAE, 0x7D, 0x01, 0x01, 0x00, 0x00, 0x00]
            ack: [0x7D, 0x01, 0x01]
          command_temperature:
            # Original lambda: uint8_t tar... (truncated)
            cmd: [0xAE, 0x7D, 0x01, 0x00, 0x00, 0x00, 0x00] # Placeholder for target
            value_offset: 3 # Target temperature goes here
            value_encode: none # Needs custom encoding logic
            ack: [0x7D, 0x01, 0x00] # Placeholder
