name: "Homenet2MQTT (Dev)"
version: "dev"
slug: "h2m-dev"
description: "Bridge between RS485 HomeNet devices and MQTT (supports multi-port/topic mapping)"
url: "https://github.com/wooooooooooook/RS485-HomeNet-to-MQTT-bridge"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
image: "nubiz/homenet2mqtt"
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
options:
  log_level: info
  mqtt_url: mqtt://core-mosquitto:1883
  mqtt_need_login: true
  mqtt_user: "addons"
  mqtt_passwd: ""
  config_files:
    - default.homenet_bridge.yaml
  mqtt_topic_prefix: homenet2mqtt
hassio_role: default
hassio_api: true
uart: true
services:
  - mqtt:need
schema:
  log_level: list(trace|debug|info|warning|error|fatal)
  mqtt_url: str
  mqtt_need_login: bool
  mqtt_user: str?
  mqtt_passwd: str?
  mqtt_topic_prefix: str?
  config_files:
    - str
ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: mdi:crop-landscape

